// Categorias:
// Notebooks // Televisores // Entretenimiento // Celulares // Impresoras // Heladeras // Cafeteras
// Tablets
const productos = [
  {
    nombre: 'Notebook Lenovo de 14" HD',
    descripcion: "",
    precio: 70000,
    id: 1,
    imagen: "test-product-note.jpg",
    categoria: "Notebooks",
    destacado: true,
    oferta: false,
  },
  {
    nombre: "Playstation 5",
    descripcion: "",
    precio: 64000,
    id: 2,
    imagen: "ps5.jpg",
    categoria: "Entretenimiento",
    destacado: true,
    oferta: false,
  },
  {
    nombre: "Smart TV PHILIPS 43 pulgadas",
    descripcion: "",
    precio: 78000,
    id: 3,
    imagen: "test-product-tv.jpg",
    categoria: "Televisores",
    destacado: true,
    oferta: false,
  },
  {
    nombre: "Celular Samsung S22",
    descripcion: "",
    precio: 58000,
    id: 4,
    imagen: "test-s22.jpg",
    categoria: "Celulares",
    destacado: true,
    oferta: false,
  },
  {
    nombre: "Impresora Epson multifunción",
    descripcion: "",
    precio: 19990,
    id: 5,
    imagen: "impresora-epson-multifuncion.jpg",
    categoria: "Impresoras",
    destacado: true,
    oferta: false,
  },
  {
    nombre: "Notebook Lenovo IDEAPAD 5",
    descripcion: "",
    precio: 114000,
    id: 6,
    imagen: "notebook-lenovo-ideapad5.jpg",
    categoria: "Notebooks",
    destacado: true,
    oferta: false,
  },
  {
    nombre: "Smart TV Phillips 70",
    descripcion: "",
    precio: 196370,
    id: 7,
    imagen: "tv-smart-tv-70-pulgadas.jpg",
    categoria: "Televisores",
    destacado: true,
    oferta: false,
  },
  {
    nombre: "Heladera Samsung no frost",
    descripcion: "",
    precio: 169999,
    id: 8,
    imagen: "heladera-samsung-nofrost.png",
    categoria: "Heladeras",
    destacado: true,
    oferta: false,
  },
  {
    nombre: "Notebook Dell JH94XWH",
    descripcion: "",
    precio: 86999,
    id: 9,
    imagen: "notebook-dell-jh94xwh.jpg",
    categoria: "Notebooks",
    destacado: true,
    oferta: false,
  },
  {
    nombre: "Cafetera EXPRESS DE LONGHI",
    descripcion: "",
    precio: 118000,
    id: 10,
    imagen: "cafetera-express-de-longhi.jpg",
    categoria: "Cafeteras",
    destacado: true,
    oferta: false,
  },
  {
    nombre: "Tablet Samsung A8",
    descripcion:
      'Tablet de 10.5" TFT WUXGA (1920 x 1200). Procesador Octa Core (CPU speed 2 GHz)',
    precio: 47500,
    precioantes: 61750,
    id: 11,
    imagen: "tablet-samsung-a8.jpg",
    categoria: "Tablets",
    destacado: false,
    oferta: true,
    descuento: 30,
  },
  {
    nombre: "Notebook PCBOX PCB",
    descripcion: 'Notebook - Cloubook. Pantalla 14" FHD (1920x1080 Px)',
    precio: 38500,
    precioantes: 48000,
    id: 12,
    imagen: "notebook-pcbox-celeron.jpg",
    categoria: "Notebooks",
    destacado: false,
    oferta: true,
    descuento: 25,
  },
  {
    nombre: "Lavarropas Dream Concept",
    descripcion: "Panel electronico. CDA (control digital de agitacion)",
    precio: 45760,
    precioantes: 35200,
    id: 13,
    imagen: "lavarropas-automatico-dream.jpg",
    categoria: "Lavarropas",
    destacado: false,
    oferta: true,
    descuento: 30,
  },
  {
    nombre: "Tablet Lenovo 8505",
    descripcion:
      "La portabilidad de una gran tablet para el entretenimiento y la comodidad",
    precio: 23475,
    precioantes: 18780,
    id: 14,
    imagen: "./public/images/tablet-lenovo-8505fs.jpg",
    categoria: "Tablets",
    destacado: false,
    oferta: true,
    descuento: 25,
  },
];

module.exports = productos;
