// Categorias:
// Notebooks // Televisores // Entretenimiento // Celulares // Impresoras // Heladeras // Cafeteras
const productos = [
  {
    nombre: 'Notebook Lenovo de 14" HD',
    descripcion: "",
    precio: 70000,
    id: 1,
    imagen: "test-product-note.jpg",
    categoria: "Notebooks",
    destacado: true,
    oferta: false,
  },
  {
    nombre: "Playstation 5",
    descripcion: "",
    precio: 64000,
    id: 2,
    imagen: "ps5.jpg",
    categoria: "Entretenimiento",
    destacado: true,
    oferta: false,
  },
  {
    nombre: "Smart TV PHILIPS 43 pulgadas",
    descripcion: "",
    precio: 78000,
    id: 3,
    imagen: "test-product-tv.jpg",
    categoria: "Televisores",
    destacado: true,
    oferta: false,
  },
  {
    nombre: "Celular Samsung S22",
    descripcion: "",
    precio: 58000,
    id: 4,
    imagen: "test-s22.jpg",
    categoria: "Celulares",
    destacado: true,
    oferta: false,
  },
  {
    nombre: "Impresora Epson multifunción",
    descripcion: "",
    precio: 19990,
    id: 5,
    imagen: "impresora-epson-multifuncion.jpg",
    categoria: "Impresoras",
    destacado: true,
    oferta: false,
  },
  {
    nombre: "Notebook Lenovo IDEAPAD 5",
    descripcion: "",
    precio: 114000,
    id: 6,
    imagen: "notebook-lenovo-ideapad5.jpg",
    categoria: "Notebooks",
    destacado: true,
    oferta: false,
  },
  {
    nombre: "Smart TV Phillips 70",
    descripcion: "",
    precio: 196370,
    id: 7,
    imagen: "tv-smart-tv-70-pulgadas.jpg",
    categoria: "Televisores",
    destacado: true,
    oferta: false,
  },
  {
    nombre: "Heladera Samsung no frost",
    descripcion: "",
    precio: 169999,
    id: 8,
    imagen: "heladera-samsung-nofrost.png",
    categoria: "Heladeras",
    destacado: true,
    oferta: false,
  },
  {
    nombre: "Notebook Dell JH94XWH",
    descripcion: "",
    precio: 86999,
    id: 9,
    imagen: "notebook-dell-jh94xwh.jpg",
    categoria: "Notebooks",
    destacado: true,
    oferta: false,
  },
  {
    nombre: "Cafetera EXPRESS DE LONGHI",
    descripcion: "",
    precio: 118000,
    id: 10,
    imagen: "cafetera-express-de-longhi.jpg",
    categoria: "Cafeteras",
    destacado: true,
    oferta: false,
  },
];

module.exports = productos;
